wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
number_hidden:
  value: 5
optimizer:
  value: momentum
weight_init:
  value: xavier
