wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
number_hidden:
  value: 3
optimizer:
  value: nadam
weight_init:
  value: random
