wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
number_hidden:
  value: 4
optimizer:
  value: rmsprop
weight_init:
  value: xavier
