wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
hidden_size:
  value: 32
learning_rate:
  value: 0.001
number_hidden:
  value: 4
optimizer:
  value: nesterov
weight_init:
  value: xavier
