_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 64
beta:
    value: 0.95
beta1:
    value: 0.9
beta2:
    value: 0.999
epochs:
    value: 5
eps:
    value: 1e-08
gamma:
    value: 0.9
hidden_inputsize:
    value: 64
learning_rate:
    value: 0.001
loss:
    value: squared
net_input_size:
    value: 784
net_output_size:
    value: 10
number_hidden:
    value: 3
optimizer:
    value: momentum
weight_decay:
    value: 0.0005
weight_init:
    value: random
