_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: tanh
batch_size:
    value: 16
epochs:
    value: 5
hidden_size:
    value: 128
learning_rate:
    value: 0.001
number_hidden:
    value: 5
optimizer:
    value: nadam
weight_init:
    value: xavier
