wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.001
number_hidden:
  value: 4
optimizer:
  value: adam
weight_init:
  value: xavier
