wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 10
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
number_hidden:
  value: 5
optimizer:
  value: sgd
weight_init:
  value: xavier
