wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
hidden_size:
  value: 128
learning_rate:
  value: 0.001
number_hidden:
  value: 3
optimizer:
  value: rmsprop
weight_init:
  value: xavier
