wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_size:
  value: 128
learning_rate:
  value: 0.001
number_hidden:
  value: 4
optimizer:
  value: sgd
weight_init:
  value: random
