wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.001
number_hidden:
  value: 4
optimizer:
  value: nesterov
weight_init:
  value: random
