wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
number_hidden:
  value: 5
optimizer:
  value: nesterov
weight_init:
  value: xavier
