wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 10
hidden_inputsize:
  value: 32
learning_rate:
  value: 0.0001
number_hidden:
  value: 3
optimizer:
  value: nesterov
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
